/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PPlanIdRouteImport } from './routes/p.$planId'
import { Route as APlanIdRouteImport } from './routes/a.$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPlanIdRoute = PPlanIdRouteImport.update({
  id: '/p/$planId',
  path: '/p/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const APlanIdRoute = APlanIdRouteImport.update({
  id: '/a/$planId',
  path: '/a/$planId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a/$planId': typeof APlanIdRoute
  '/p/$planId': typeof PPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a/$planId': typeof APlanIdRoute
  '/p/$planId': typeof PPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a/$planId': typeof APlanIdRoute
  '/p/$planId': typeof PPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/a/$planId' | '/p/$planId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a/$planId' | '/p/$planId'
  id: '__root__' | '/' | '/a/$planId' | '/p/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  APlanIdRoute: typeof APlanIdRoute
  PPlanIdRoute: typeof PPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$planId': {
      id: '/p/$planId'
      path: '/p/$planId'
      fullPath: '/p/$planId'
      preLoaderRoute: typeof PPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$planId': {
      id: '/a/$planId'
      path: '/a/$planId'
      fullPath: '/a/$planId'
      preLoaderRoute: typeof APlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  APlanIdRoute: APlanIdRoute,
  PPlanIdRoute: PPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
